### ISSUE TITLE
Pass IOLoop.ERROR on error?

### ISSUE THREAD

**Issue by schlamar** [saghul/tornaduv#19]
I just stumbled across this one: https://github.com/saghul/tornaduv/blob/master/tornaduv/__init__.py#L222

Shouldn't we pass IOLoop.ERROR to the IOStream in this case?

**Comment by saghul** [comment]
I don't recall when Tornado uses that from the top of my head :-S The point of that code is to force the code to call a read or write operation and get the actual error, since we don't really know what it is.
